In [1]:
import pandas as ps

In [38]:
data = ps.read_csv("C:/Users/wvx67826/git/AIPID_Cryostat/src/data/testData/EM_LS336_Openloop_heaterStep=5_first.dat")

In [39]:
data

            Time(s)  SetTemp(K)  Temp(K)  HeatPower      P     I    D
0      1.670519e+09        80.0  127.527        0.0  130.0  50.0  0.0
1      1.670519e+09        80.0  127.540        0.0  130.0  50.0  0.0
2      1.670519e+09        80.0  127.546        0.0  130.0  50.0  0.0
3      1.670519e+09        80.0  127.548        0.0  130.0  50.0  0.0
4      1.670519e+09        80.0  127.542        0.0  130.0  50.0  0.0
...             ...         ...      ...        ...    ...   ...  ...
12211  1.670581e+09        80.0  335.430       30.0  130.0  50.0  0.0
12212  1.670581e+09        80.0  335.459       30.0  130.0  50.0  0.0
12213  1.670581e+09        80.0  335.495       30.0  130.0  50.0  0.0
12214  1.670581e+09        80.0  335.538       30.0  130.0  50.0  0.0
12215  1.670581e+09        80.0  335.495       30.0  130.0  50.0  0.0

[12216 rows x 7 columns]

In [40]:
data['I'].isna()

0        False
1        False
2        False
3        False
4        False
         ...
12211    False
12212    False
12213    False
12214    False
12215    False
Name: I, Length: 12216, dtype: bool

In [41]:
data2 = data.dropna()

In [42]:
data2['I'].isna()

0        False
1        False
2        False
3        False
4        False
         ...
12211    False
12212    False
12213    False
12214    False
12215    False
Name: I, Length: 12193, dtype: bool

In [43]:
data3 = data2.drop(data2[data2.HeatPower>100].index)

In [44]:
data3

            Time(s)  SetTemp(K)  Temp(K)  HeatPower      P     I    D
0      1.670519e+09        80.0  127.527        0.0  130.0  50.0  0.0
1      1.670519e+09        80.0  127.540        0.0  130.0  50.0  0.0
2      1.670519e+09        80.0  127.546        0.0  130.0  50.0  0.0
3      1.670519e+09        80.0  127.548        0.0  130.0  50.0  0.0
4      1.670519e+09        80.0  127.542        0.0  130.0  50.0  0.0
...             ...         ...      ...        ...    ...   ...  ...
12211  1.670581e+09        80.0  335.430       30.0  130.0  50.0  0.0
12212  1.670581e+09        80.0  335.459       30.0  130.0  50.0  0.0
12213  1.670581e+09        80.0  335.495       30.0  130.0  50.0  0.0
12214  1.670581e+09        80.0  335.538       30.0  130.0  50.0  0.0
12215  1.670581e+09        80.0  335.495       30.0  130.0  50.0  0.0

[12176 rows x 7 columns]

In [45]:
data3.to_csv("C:/Users/wvx67826/Desktop/PID//EM_LS336_Openloop_heaterStep=5_first.dat")